# Generated by Django 4.0.3 on 2022-03-21 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_post_options_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='owner',
            new_name='author',
        ),
    ]
